version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build:
    executor:
      name: node/default
      tag: '14.16.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run validate
      - run:
          command: npm run test
