export enum TestAutomationId {
  CounterValue = 'counter-value',
  IncreaseButton = 'increase-btn',
  DecreaseButton = 'decrease-btn',
  ConfirmDialogYesButton = 'confirm-yes',
  ConfirmDialogNoButton = 'confirm-no',
  CounterResetButton = 'counter-reset-btn',
  CounterSetButton = 'counter-set-btn',
  CounterAmountSlider = 'amount-slider',
  CounterAmountInput = 'counter-amount-input',
  FormSaveButton = 'form-save-btn',
  FormFieldError = 'form-field-error',
  ModalDismissIcon = 'modal-dismiss-icon',
  ModalOverlay = 'modal-overlay',
  AppSettingsButton = 'app-settings-btn',
  ResetSettingsButton = 'reset-settings-btn',
  WarningText = 'warning-text',
}
